### ISSUE TITLE
Register with Ansible-Galaxy

### ISSUE THREAD

**Issue by dennisdegreef** [PowerDNS/pdns-ansible#1]
It would be nice to register this package to ansible galaxy when stable

**Comment by pieterlexis** [comment]
this is the plan after more tests have been made (and passed).

**Comment by lazouz** [comment]
I think you should really consider doing it : now, there are some forks of this role on galaxy, and theses forks are not up-to-date.

Moreover, having a role registered under "powerDNS" author will be much more legitimate !

**Comment by atosatto** [comment]
Here it is the role finally available on galaxy: https://galaxy.ansible.com/PowerDNS/pdns/.
The latest release, `v1.0.0`, contains tons of improvements and, finally, tests! :)

**Comment by lazouz** [comment]
awesome :D !
