### ISSUE TITLE
Accept a list of values for "content"

### ISSUE THREAD

**Issue by href** [PowerDNS/pdns-ansible#108]
Take the following records:

    A foo.example.org. 111.111.111.111
    A foo.example.org. 111.111.111.112

To add these records, one would define them using `exclusive: False`, so that the first record does not get replaced by the second record if added in succession.

I think it might make sense to add another option: Use `exclusive: True`, but allow `content` to be a list of values. In this case the module would make sure that it is exactly this list that is present, and nothing else of that record.

At least in our case this would be a lot simpler, since we usually have the whole list of values at hand anyway.

I'm happy to implement this myself. Let me know if you are interested in a PR to that effect.

**Comment by pieterlexis** [comment]
This role doesn't support adding any records to the configured PowerDNS instance. I _think_ you're using a role or library that does this?

**Comment by href** [comment]
🤦 Totally opened an issue on the wrong tracker. Sorry for that!
