### ISSUE TITLE
README needs addressing regarding mysql

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns-ansible#40]
line 226 (give or take) of https://github.com/PowerDNS/pdns-ansible/blob/master/README.md makes no sense to me: it says host,user,dbname,pw become mandatory: dbname is missing in example, and the example says `priv_*` 

also formatting below priv_host is wrong (I didn't touch in my PR b/c I haven't looked at code)

**Comment by jpmens** [comment]
It also clearly states `database servers are not (and will not) be installed by this role`.

However, further down in the README it says

`Credentials to create the PowerDNS MySQL backend databases and users. For example:`

This needs clarification. Does the role create or not create the database?

**Comment by atosatto** [comment]
Ehi @jpmens, let's merge your PR #39 as a baseline for further improvements to the README.

**Comment by atosatto** [comment]
I tried to make the README much more clear on this.
Feel free to open again this issue if it's still confusing.
Thanks for the feedback!
