### ISSUE TITLE
init file for mysql-backend not found on centos 7

### ISSUE THREAD

**Issue by h33x0** [PowerDNS/pdns-ansible#58]
Hi!
When playbook runs on Centos 7, path to file concatente from server version, cutted with regex_replace. Regex based on '-rc' substring, but centos package version from master repo doesn't contains it - only build version and commit hash.

I fix this issue and attach small patch for role below.

```
Index: tasks/database-mysql.yml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tasks/database-mysql.yml	(revision cc4ab566710794d64b8ce5e6444a922e49e0b549)
+++ tasks/database-mysql.yml	(date 1555399095000)
@@ -63,7 +63,7 @@
 
 - name: Define the PowerDNS Authoritative Server database MySQL schema file path on RedHat >= 7
   set_fact:
-    _pdns_mysql_schema_file: "/usr/share/doc/pdns-backend-mysql-{{ _pdns_running_version | regex_replace('-rc[\\d]*$', '') }}/schema.mysql.sql"
+    _pdns_mysql_schema_file: "/usr/share/doc/pdns-backend-mysql-{{ _pdns_running_version | regex_replace('\\.\\d+\\.[\\d\\w]+$', '') }}/schema.mysql.sql"
   when: ansible_os_family == 'RedHat' and ansible_distribution_major_version | int >= 7
 
 - name: Define the PowerDNS Authoritative Server database MySQL schema file path on Debian
```

regards,
Anton

**Comment by atosatto** [comment]
Hi @h33x0 thanks for this suggestion!
We've recently changed our packages version numbering convention for "master builds".
https://github.com/PowerDNS/pdns-ansible/pull/69 implements a new regex that should fix the issue you reported.
Feel free to reopen the ticket in case this still does not work for you.
