### ISSUE TITLE
Trouble running tests with tox

### ISSUE THREAD

**Issue by Godwottery** [PowerDNS/pdns-ansible#63]
I am trying to find out why the test are failing for my pull-request. In order to do this I am trying to run tests locally. 

I am failing to successfully run them, even though I am running the "proper" HEAD-revision, ie from this repo and not from my fork. This revision passes tests from Travis CI. What am I doing wrong. I have installed all dependencies (tox, docker) on the machines and checked out the newest commit.

On both Fedora and Ubuntu I get the following error messages when running '''tox'''
``
.... ( removed to save space ) 
TASK [pdns-ansible : Install the PowerDNS Authoritative Server] ****************
.... ( removed to save space )
failed: [centos-7] (item={'key': u'gsqlite3', 'value': {u'dnssec': True, u'database': u'/var/lib/powerdns/pdns.db'}}) => {"item": {"key": "gsqlite3", "value": {"database": "/var/lib/powerdns/pdns.db", "dnssec": true}}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1562862716.65-269451528487074 `\" && echo ansible-tmp-1562862716.65-269451528487074=\"` echo ~/.ansible/tmp/ansible-tmp-1562862716.65-269451528487074 `\" ), exited with result 1", "unreachable": true}
    failed: [debian-8] (item={'key': u'gsqlite3', 'value': {u'dnssec': True, u'database': u'/var/lib/powerdns/pdns.db'}}) => {"item": {"key": "gsqlite3", "value": {"database": "/var/lib/powerdns/pdns.db", "dnssec": true}}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1562862716.59-142468410910534 `\" && echo ansible-tmp-1562862716.59-142468410910534=\"` echo ~/.ansible/tmp/ansible-tmp-1562862716.59-142468410910534 `\" ), exited with result 1", "unreachable": true}
    failed: [debian-9] (item={'key': u'gsqlite3', 'value': {u'dnssec': True, u'database': u'/var/lib/powerdns/pdns.db'}}) => {"item": {"key": "gsqlite3", "value": {"database": "/var/lib/powerdns/pdns.db", "dnssec": true}}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1562862716.6-114727032125280 `\" && echo ansible-tmp-1562862716.6-114727032125280=\"` echo ~/.ansible/tmp/ansible-tmp-1562862716.6-114727032125280 `\" ), exited with result 1", "unreachable": true}
    fatal: [debian-8]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": {"key": "gsqlite3", "value": {"database": "/var/lib/powerdns/pdns.db", "dnssec": true}}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1562862716.59-142468410910534 `\" && echo ansible-tmp-1562862716.59-142468410910534=\"` echo ~/.ansible/tmp/ansible-tmp-1562862716.59-142468410910534 `\" ), exited with result 1", "unreachable": true}, {"_ansible_item_result": true, "item": {"key": "gmysql", "value": {"dbname": "debian-8", "host": "mysql", "password": "pdns", "user": "pdns"}}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1562862717.39-96503054208728 `\" && echo ansible-tmp-1562862717.39-96503054208728=\"` echo ~/.ansible/tmp/ansible-tmp-1562862717.39-96503054208728 `\" ), exited with result 1", "unreachable": true}]}
    failed: [debian-8] (item={'key': u'gmysql', 'value': {u'dbname': u'debian-8', u'user': u'pdns', u'host': u'mysql', u'password': u'pdns'}}) => {"item": {"key": "gmysql", "value": {"dbname": "debian-8", "host": "mysql", "password": "pdns", "user": "pdns"}}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1562862717.39-96503054208728 `\" && echo ansible-tmp-1562862717.39-96503054208728=\"` echo ~/.ansible/tmp/ansible-tmp-1562862717.39-96503054208728 `\" ), exited with result 1", "unreachable": true}
    fatal: [debian-9]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": {"key": "gsqlite3", "value": {"database": "/var/lib/powerdns/pdns.db", "dnssec": true}}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1562862716.6-114727032125280 `\" && echo ansible-tmp-1562862716.6-114727032125280=\"` echo ~/.ansible/tmp/ansible-tmp-1562862716.6-114727032125280 `\" ), exited with result 1", "unreachable": true}, {"_ansible_item_result": true, "item": {"key": "gmysql", "value": {"dbname": "debian-9", "host": "mysql", "password": "pdns", "user": "pdns"}}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1562862717.41-76417805522068 `\" && echo ansible-tmp-1562862717.41-76417805522068=\"` echo ~/.ansible/tmp/ansible-tmp-1562862717.41-76417805522068 `\" ), exited with result 1", "unreachable": true}]}
    failed: [debian-9] (item={'key': u'gmysql', 'value': {u'dbname': u'debian-9', u'user': u'pdns', u'host': u'mysql', u'password': u'pdns'}}) => {"item": {"key": "gmysql", "value": {"dbname": "debian-9", "host": "mysql", "password": "pdns", "user": "pdns"}}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1562862717.41-76417805522068 `\" && echo ansible-tmp-1562862717.41-76417805522068=\"` echo ~/.ansible/tmp/ansible-tmp-1562862717.41-76417805522068 `\" ), exited with result 1", "unreachable": true}
    fatal: [centos-7]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": {"key": "gsqlite3", "value": {"database": "/var/lib/powerdns/pdns.db", "dnssec": true}}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1562862716.65-269451528487074 `\" && echo ansible-tmp-1562862716.65-269451528487074=\"` echo ~/.ansible/tmp/ansible-tmp-1562862716.65-269451528487074 `\" ), exited with result 1", "unreachable": true}, {"_ansible_item_result": true, "item": {"key": "gmysql", "value": {"dbname": "centos-7", "host": "mysql", "password": "pdns", "user": "pdns"}}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1562862717.38-100460596510562 `\" && echo ansible-tmp-1562862717.38-100460596510562=\"` echo ~/.ansible/tmp/ansible-tmp-1562862717.38-100460596510562 `\" ), exited with result 1", "unreachable": true}]}
    failed: [centos-7] (item={'key': u'gmysql', 'value': {u'dbname': u'centos-7', u'user': u'pdns', u'host': u'mysql', u'password': u'pdns'}}) => {"item": {"key": "gmysql", "value": {"dbname": "centos-7", "host": "mysql", "password": "pdns", "user": "pdns"}}, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1562862717.38-100460596510562 `\" && echo ansible-tmp-1562862717.38-100460596510562=\"` echo ~/.ansible/tmp/ansible-tmp-1562862717.38-100460596510562 `\" ), exited with result 1", "unreachable": true}
``

**Comment by pieterlexis** [comment]
fixed in master
