### ISSUE TITLE
'_pdns_package_version' is undefined

### ISSUE THREAD

**Issue by florath** [PowerDNS/pdns-ansible#84]
Using the latest released version results in the following error:

> FAILED! => {"changed": false, "msg": "AnsibleError: An unhandled exception occurred while templating '{{ default_pdns_service_overrides }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{  { 'User'  : pdns_user\n    , 'Group' : pdns_group\n    } if _pdns_package_version is version('4.3', operator='ge')\n      else {}\n}}'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: Version comparison: '_pdns_package_version' is undefined"}

Running Ubuntu 20.04 which comes with pdns 4.2.1

**Comment by pieterlexis** [comment]
Hrm, what ansible version are you using?

**Comment by florath** [comment]
ansible 2.9.12 (in a virtualenv)
python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]

**Comment by pieterlexis** [comment]
I've managed to reproduce this. It shows up indeed once `pdns_service_overrides` is not defined. I'll investigate further.
