### ISSUE TITLE
CentOS Stream 8/pdns 4.3.1  tasks/database-mysql gets schema location wrong

### ISSUE THREAD

**Issue by dlcarmean** [PowerDNS/pdns-ansible#92]
On the below-described system, the role tries to load schema.mysql.sql from /usr/share/doc/pdns-backend-mysql/, but the pdns-backend-mysql RPM places it in /usr/share/doc/pdns/

$ rpm -ql pdns-backend-mysql | grep '/schema.mysql.sql'
/usr/share/doc/pdns/schema.mysql.sql

$ rpm -qa | grep pdns
pdns-4.3.1-1.el8.x86_64
pdns-backend-mysql-4.3.1-1.el8.x86_64

$ uname -a
Linux vm1-dns.lax.... 4.18.0-240.el8.x86_64 #1 SMP Fri Sep 25 19:48:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/redhat-release 
CentOS Stream release 8

**Comment by pieterlexis** [comment]
What repo does this package come from? PowerDNS or EPEL?

**Comment by dlcarmean** [comment]
Yes, the only vars I set to run the playbook/role were the db credentials. I have not checked other version combos/repos/builds.

**Comment by pieterlexis** [comment]
so it looks like EPEL ships the file in a different directory than PowerDNS does. A work-around here is using

```yaml
pdns_install_repo: "{{ pdns_auth_powerdns_repo_43 }}"
```

We'll need to find a way to detect this case. I've tried with `with_first_found`, but that does not seem to work on files on the target.
